from weakref import finalize

from gimmik import HIPMatMul, OPERAND_BUFFER, SIG_ABC, SIG_BC

from pyfr.backends.base import NotSuitableError
from pyfr.backends.hip.provider import HIPKernel, HIPKernelProvider


class HIPGiMMiKKernels(HIPKernelProvider):
    # Call signatures we are able to marshal arguments for
    sigs = frozenset({SIG_BC, SIG_ABC})

    # Types of the arguments a kernel can ask to be passed
    argtypes = {'a': 'P', 'n': 'i', 'b': 'P', 'ldb': 'i', 'c': 'P',
                'ldc': 'i'}

    def __init__(self, backend):
        super().__init__(backend)

        # Maximum number of kernels to consider
        self.nkerns = backend.cfg.getint('backend-hip', 'gimmik-nkerns', 8)

        # Number of benchmarking runs
        self.nbench = backend.cfg.getint('backend-hip', 'gimmik-nbench', 5)

        # Kernel cache
        self._mul_kerns = {}

    def mul(self, a, b, out, alpha=1.0, beta=0.0):
        # Ensure the matrices are compatible
        if a.nrow != out.nrow or a.ncol != b.nrow or b.ncol != out.ncol:
            raise ValueError('Incompatible matrices for out = a*b')

        # Check that A is constant
        if 'const' not in a.tags:
            raise NotSuitableError('GiMMiK requires a constant a matrix')

        # Fetch the matrix
        arr = a.get()

        # Dimensions
        n = b.ncol
        ldb, ldc = b.leaddim, out.leaddim

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        # Cache key
        ckey = (a.mid, alpha, beta, aligne)

        # Check the kernel cache
        try:
            kern, mm, kmeta, bufs, dt = self._mul_kerns[ckey]
        except KeyError:
            ifac = self.backend.autotune_ifac
            kname = f'gimmik_mm_{arr.shape[0]}x{arr.shape[1]}'
            kdata = None
            best_kern = None

            mm = HIPMatMul(alpha*arr, beta=beta, aligne=aligne)
            kgen = mm.kernels(a.dtype, kname=kname, sigs=self.sigs,
                              gcn_arch=self.backend.props['gcn_arch_name'],
                              warp_size=self.backend.props['warp_size'])

            # Benchmark the sequence of kernels generated by GiMMiK
            try:
                with self._bench_data(save=[out], rand=[b]):
                    for i in range(self.nkerns):
                        src, meta = kgen.send(kdata)

                        bufs = self._operand_bufs(mm, meta, n, ldb, ldc)
                        if bufs is None:
                            continue

                        argt = [self.argtypes[k] for k in meta['args']]
                        kern = self._build_kernel(kname, src, argt)

                        kargs = self._kernel_args(meta, bufs, n, b, ldb,
                                                  out, ldc)
                        lcfg = mm.launch_config(meta, n)
                        params = kern.make_params(lcfg['grid'],
                                                  lcfg['block'])
                        params.set_args(*kargs)

                        # Obtain the runtime
                        dt = self._benchmark(
                            lambda stream: kern.exec_async(stream, params),
                            nbench=self.nbench
                        )

                        if best_kern is None or dt < ifac*best_kern[-1]:
                            best_kern = kern, mm, meta, bufs, dt

                        kdata = {
                            'runtime': dt,
                            'registers': kern.nreg,
                            'local_mem': kern.local_mem
                        }
            except StopIteration:
                pass

            # GiMMiK declines an operator by offering no kernels for it
            if best_kern is None:
                raise NotSuitableError('Matrix is inappropriate for GiMMiK')

            # Update the cache
            self._mul_kerns[ckey] = kern, mm, kmeta, bufs, dt = best_kern
            finalize(a, lambda: self._mul_kerns.pop(ckey))

        # Set the parameters, rebinding the operands to these matrices
        kargs = self._kernel_args(kmeta, bufs, n, b, ldb, out, ldc)
        lcfg = mm.launch_config(kmeta, n)
        params = kern.make_params(lcfg['grid'], lcfg['block'])
        params.set_args(*kargs)

        class MulKernel(HIPKernel):
            def add_to_graph(self, graph, deps):
                return graph.graph.add_kernel(params, deps)

            def run(self, stream):
                kern.exec_async(stream, params)

        return MulKernel(mats=[a, b, out], dt=dt)

    def _operand_bufs(self, mm, meta, n, ldb, ldc):
        # Buffers for the operands GiMMiK asks us to prepare, else None
        bufs = {}

        for name, spec in mm.operands(meta, n, ldb, ldc).items():
            if name != 'a' or spec['kind'] != OPERAND_BUFFER:
                return None

            buf = self.backend.hip.mem_alloc(spec['nbytes'])
            self.backend.hip.memcpy(buf, mm.pack_a(meta), spec['nbytes'])

            bufs[name] = buf

        return bufs

    @staticmethod
    def _kernel_args(meta, bufs, n, b, ldb, out, ldc):
        vals = {'n': n, 'b': b, 'ldb': ldb, 'c': out, 'ldc': ldc} | bufs

        return [vals[name] for name in meta['args']]
