from weakref import finalize

import gimmik

from pyfr.backends.base import NotSuitableError
from pyfr.backends.cuda.provider import CUDAKernel, CUDAKernelProvider


class CUDAGiMMiKKernels(CUDAKernelProvider):
    # Generators to consult, in order of preference
    matmuls = [gimmik.PTXMatMul, gimmik.CUDAMatMul]

    # Call signatures we are able to marshal arguments for
    sigs = frozenset({gimmik.SIG_BC, gimmik.SIG_ABC, gimmik.SIG_BDESC_C,
                      gimmik.SIG_BDESC_CDESC})

    # Types of the arguments a kernel can ask to be passed
    argtypes = {'a': 'P', 'n': 'i', 'b': 'P', 'ldb': 'i', 'c': 'P',
                'ldc': 'i', 'b_desc': 'P', 'c_desc': 'P'}

    def __init__(self, backend):
        super().__init__(backend)

        # Maximum number of kernels to consider
        self.nkerns = backend.cfg.getint('backend-cuda', 'gimmik-nkerns', 10)

        # Number of benchmarking runs
        self.nbench = backend.cfg.getint('backend-cuda', 'gimmik-nbench', 5)

        # Kernel cache
        self._mul_kerns = {}

        # GPU Properties used in generator
        self.cc = self.backend.cuda.compute_capability()
        self.smem_max = self.backend.cuda.smem_info()

    def mul(self, a, b, out, alpha=1.0, beta=0.0):
        # Ensure the matrices are compatible
        if a.nrow != out.nrow or a.ncol != b.nrow or b.ncol != out.ncol:
            raise ValueError('Incompatible matrices for out = a*b')

        # Check that A is constant
        if 'const' not in a.tags:
            raise NotSuitableError('GiMMiK requires a constant a matrix')

        # Dimensions
        n, ldb, ldc = b.ncol, b.leaddim, out.leaddim

        # Alignment
        if 'align' in b.tags and 'align' in out.tags:
            aligne = self.backend.alignb // b.itemsize
        else:
            aligne = None

        # Values of the arguments a kernel can ask to be passed
        vals = {'n': n, 'b': b, 'ldb': ldb, 'c': out, 'ldc': ldc}

        # Cache key
        ckey = (a.mid, alpha, beta, aligne, ldb, ldc)

        try:
            kern, mm, kmeta, bufs, dt = self._mul_kerns[ckey]
        except KeyError:
            # Fetch the matrix and premultiply
            arr = alpha*a.get()

            with self._bench_data(save=[out], rand=[b]):
                best_kern = self._autotune(arr, beta, aligne, n, b, out)

            # GiMMiK declines an operator by offering no kernels for it
            if best_kern is None:
                raise NotSuitableError('Matrix is inappropriate for GiMMiK')

            self._mul_kerns[ckey] = kern, mm, kmeta, bufs, dt = best_kern
            finalize(a, lambda: self._mul_kerns.pop(ckey))

        # Set the parameters, rebinding the operands to these matrices
        kargs = self._kernel_args(mm, kmeta, vals, bufs, n, ldb, ldc)
        lcfg = mm.launch_config(kmeta, n)
        params = kern.make_params(lcfg['grid'], lcfg['block'], 0)
        params.set_args(*kargs)

        class MulKernel(CUDAKernel):
            def add_to_graph(self, graph, deps):
                return graph.graph.add_kernel(params, deps)

            def run(self, stream):
                kern.exec_async(stream, params)

        return MulKernel(mats=[a, b, out], dt=dt)

    def _autotune(self, arr, beta, aligne, n, b, out):
        m, k = arr.shape

        # Consult each generator in turn, taking the first with a kernel
        for mmcls in self.matmuls:
            kname = f'gimmik_mm_{m}x{k}_{mmcls.platform}'

            mm = mmcls(arr, beta=beta, aligne=aligne, n=n, ldb=b.leaddim,
                       ldc=out.leaddim)
            kgen = mm.kernels(arr.dtype, kname=kname, sigs=self.sigs,
                              compute_capability=self.cc,
                              smem_max=self.smem_max)

            best_kern = self._mul(kname, mm, kgen, n, b, out)
            if best_kern is not None:
                return best_kern

        return None

    def _mul(self, kname, mm, kgen, n, b, out):
        ifac = self.backend.autotune_ifac
        ldb, ldc = b.leaddim, out.leaddim
        vals = {'n': n, 'b': b, 'ldb': ldb, 'c': out, 'ldc': ldc}
        kdata = None
        best_kern = None

        # Benchmark the sequence of kernels generated by GiMMiK
        try:
            for i in range(self.nkerns):
                src, meta = kgen.send(kdata)

                bufs = self._operand_bufs(mm, meta, n, ldb, ldc)
                kargs = self._kernel_args(mm, meta, vals, bufs, n, ldb, ldc)
                argt = [self.argtypes[k] for k in meta['args']]
                kern = self._build_kernel(kname, src, argt)

                # If the kernel is spilling then request more L1
                if kern.local_mem and not kern.shared_mem:
                    kern.set_shared_size(carveout=0)

                # Set the parameters
                lcfg = mm.launch_config(meta, n)
                params = kern.make_params(lcfg['grid'], lcfg['block'], 0)
                params.set_args(*kargs)

                # Obtain the runtime
                dt = self._benchmark(
                    lambda stream: kern.exec_async(stream, params),
                    nbench=self.nbench
                )

                if best_kern is None or dt < ifac*best_kern[-1]:
                    best_kern = (kern, mm, meta, bufs, dt)

                kdata = {
                    'runtime': dt,
                    'registers': kern.nreg,
                    'local_mem': kern.local_mem,
                    'shared_mem': kern.shared_mem
                }
        except StopIteration:
            pass

        return best_kern

    def _operand_bufs(self, mm, meta, n, ldb, ldc):
        # The only operand GiMMiK asks us to pack is a copy of A
        spec = mm.operands(meta, n, ldb, ldc).get('a')

        if spec is None:
            return {}
        else:
            nbytes = spec['nbytes']
            buf = self.backend.cuda.mem_alloc(nbytes)
            self.backend.cuda.memcpy(buf, mm.pack_a(meta), nbytes)

            return {'a': buf}

    def _kernel_args(self, mm, meta, vals, bufs, n, ldb, ldc):
        # Operands describe any argument the caller has to prepare itself
        operands = mm.operands(meta, n, ldb, ldc)
        kargs = []

        for name in meta['args']:
            spec = operands.get(name)

            match spec:
                # A matrix or dimension we are holding already
                case None:
                    kargs.append(vals[name])
                # An operand we packed ahead of time
                case {'kind': gimmik.OPERAND_BUFFER}:
                    kargs.append(bufs[name])
                # A tensor map over one of the matrices
                case {'kind': gimmik.OPERAND_TENSORMAP, 'operand': operand}:
                    tm = vals[operand].tensormap(spec)
                    kargs.append(tm.ctypes.data)

        return kargs
